{% set name = "tabpfn" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tabpfn-{{ version }}.tar.gz
  sha256: 4567b288bb9c8ba5971cf0634e4b0cfd752a31f751564691cb42f6fc9983fc7b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - pytorch >=1.9.0
    - scikit-learn >=0.24.2
    - pyyaml >=5.4.1
    - numpy >=1.21.2
    - requests >=2.23.0

test:
  imports:
    - tabpfn
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/automl/TabPFN
  summary: Interface for using TabPFN and library to train TabPFN'
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - NOTICE.txt

extra:
  recipe-maintainers:
    - anuprulez
