{% set name = "tabpfn" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tabpfn-{{ version }}.tar.gz
  sha256: fdfd522545f1d19c0b4953733471f797b1073ee387ea3db861ff4c43731b61da

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python 3.10
    - setuptools
    - pip
  run:
    - python >=3.10
    - pytorch >=2.1
    - scikit-learn >=1
    - scipy
    - pandas
    - einops
    - huggingface_hub
    - pydantic

test:
  imports:
    - tabpfn
  commands:
    - pip check
  requires:
    - pip
    - python 3.10

about:
  home: https://github.com/PriorLabs/TabPFN
  summary: Foundation model for tabular data
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - anuprulez
