{% set name = "tabpfn" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tabpfn-{{ version }}.tar.gz
  sha256: 6884b1bd30100852f5b37e3ae54d862eddb5eb002da67ac57422c800abdbbc09

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - pytorch >=2.1
    - scikit-learn >=1
    - scipy
    - pandas
    - einops
    - huggingface_hub

test:
  imports:
    - tabpfn
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/PriorLabs/TabPFN
  summary: Foundation model for tabular data
  license: Apache-2.0
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - anuprulez
