{% set name = "tabpfn" %}
{% set version = "2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tabpfn-{{ version }}.tar.gz
  sha256: b83988fc16f6a893ead8de7705a0d3b0c6e3240202e3cd5c8da57061d378246d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - pytorch >=2.1
    - scikit-learn >=1
    - scipy
    - pandas
    - einops
    - huggingface_hub

test:
  imports:
    - tabpfn
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/PriorLabs/TabPFN
  summary: Foundation model for tabular data
  license: Apache-2.0
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - anuprulez
