schema_version: 1

context:
  name: tabpfn
  version: "6.3.1"
  python_min: 3.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/tabpfn-${{ version }}.tar.gz
  sha256: f25f174b06934cb851e78d6f7d43603e800d03dde415546a927c1a23d018d66e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - joblib >=1.2.0
    - tabpfn-common-utils >=0.2.13
    - python >=${{ python_min }}
    - einops >=0.2.0,<0.9
    - eval-type-backport >=0.2.2
    - pandas >=1.4.0,<3
    - pydantic >=2.8.0
    - pydantic-settings >=2.10.1
    - pytorch >=2.1,<3
    - scikit-learn >=1.2.0,<1.8
    - scipy >=1.11.1,<2
    - typing_extensions >=4.12.0
    - numpy >=1.21.6,<3
    - huggingface_hub >=0.19.0,<2
tests:
  - python:
      imports:
        - tabpfn
      pip_check: true

      python_version: ${{ python_min }}.*
about:
  summary: Foundation model for tabular data
  license: Apache-2.0
  license_file:
    - LICENSE
  homepage: https://github.com/PriorLabs/TabPFN

extra:
  recipe-maintainers:
    - anuprulez
    - janjagusch
